# Generated by Django 5.2.17 on 2026-09-03 22:21

import django.db.models.deletion
import logistics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_time', models.DateTimeField()),
                ('edit_reason', models.CharField(blank=True, max_length=256)),
                ('latest', models.BooleanField()),
                ('accepted', models.BooleanField()),
                ('acceptance_comment', models.CharField(blank=True, max_length=256)),
                ('dropped', models.BooleanField(null=True)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.attendee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_time', models.DateTimeField()),
                ('edit_reason', models.CharField(blank=True, max_length=256)),
                ('latest', models.BooleanField()),
                ('winter_activities', models.BooleanField()),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.attendee')),
            ],
            options={
                'verbose_name': 'Winter Activities Logistics',
                'verbose_name_plural': 'Winter Activities Logistics',
            },
        ),
        migrations.CreateModel(
            name='Buses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Early'), (1, 'Late'), (2, 'Return')])),
                ('number', models.IntegerField()),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('leader_phone_number', models.CharField(blank=True, max_length=16, null=True)),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conference.attendee')),
                ('quarc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.quarcconference')),
            ],
            options={
                'verbose_name': 'Bus',
                'verbose_name_plural': 'Buses',
            },
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_time', models.DateTimeField()),
                ('edit_reason', models.CharField(blank=True, max_length=256)),
                ('latest', models.BooleanField()),
                ('bus_to_required', models.BooleanField()),
                ('bus_to_type', models.IntegerField(blank=True, choices=[(0, 'Early'), (1, 'Late'), (2, 'Return')], null=True)),
                ('bus_from_required', models.BooleanField()),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.attendee')),
                ('bus_from_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bus_from', to='logistics.buses', validators=[logistics.models.validate_bus_from, logistics.models.validate_bus_capacity])),
                ('bus_to_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bus_to', to='logistics.buses', validators=[logistics.models.validate_bus_to, logistics.models.validate_bus_capacity])),
            ],
            options={
                'verbose_name': 'Bus Logistics',
                'verbose_name_plural': 'Bus Logistics',
            },
        ),
        migrations.CreateModel(
            name='DinnerOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=32)),
                ('quarc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.quarcconference')),
            ],
            options={
                'verbose_name': 'Dinner Option',
                'verbose_name_plural': 'Dinner Options',
            },
        ),
        migrations.CreateModel(
            name='Dinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_time', models.DateTimeField()),
                ('edit_reason', models.CharField(blank=True, max_length=256)),
                ('latest', models.BooleanField()),
                ('dinner_required', models.BooleanField()),
                ('vegetarian', models.BooleanField(blank=True, null=True)),
                ('vegan', models.BooleanField(blank=True, null=True)),
                ('gluten_free', models.BooleanField(blank=True, null=True)),
                ('kosher', models.BooleanField(blank=True, null=True)),
                ('halal', models.BooleanField(blank=True, null=True)),
                ('other_restriction', models.CharField(blank=True, max_length=64)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.attendee')),
                ('dinner_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.dinneroptions')),
            ],
            options={
                'verbose_name': 'Dinner Logistics',
                'verbose_name_plural': 'Dinner Logistics',
            },
        ),
        migrations.CreateModel(
            name='HousingAssignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_time', models.DateTimeField()),
                ('edit_reason', models.CharField(blank=True, max_length=256)),
                ('latest', models.BooleanField()),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.attendee')),
                ('roommate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roommate', to='conference.attendee')),
            ],
            options={
                'verbose_name': 'Housing Assignment Logistics',
                'verbose_name_plural': 'Housing Assignment Logistics',
            },
        ),
        migrations.CreateModel(
            name='HousingPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_time', models.DateTimeField()),
                ('edit_reason', models.CharField(blank=True, max_length=256)),
                ('latest', models.BooleanField()),
                ('overnight_required', models.BooleanField()),
                ('needs_roommate', models.BooleanField(blank=True)),
                ('preferred_roommate_name', models.CharField(blank=True, max_length=64)),
                ('gender', models.CharField(blank=True, max_length=32)),
                ('preferred_roommate_gender', models.CharField(blank=True, max_length=32)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.attendee')),
                ('preferred_roommate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_roommate', to='conference.attendee')),
            ],
            options={
                'verbose_name': 'Housing Preferences Logistics',
                'verbose_name_plural': 'Housing Preferences Logistics',
            },
        ),
        migrations.CreateModel(
            name='MARC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_time', models.DateTimeField()),
                ('edit_reason', models.CharField(blank=True, max_length=256)),
                ('latest', models.BooleanField()),
                ('attending_marc', models.BooleanField(null=True)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.attendee')),
            ],
            options={
                'verbose_name': 'MARC Logistics',
                'verbose_name_plural': 'MARC Logistics',
            },
        ),
        migrations.CreateModel(
            name='SwagOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=32)),
                ('url', models.CharField(blank=True, max_length=32)),
                ('quarc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.quarcconference')),
            ],
            options={
                'verbose_name': 'Swag Option',
                'verbose_name_plural': 'Swag Options',
            },
        ),
        migrations.CreateModel(
            name='Swag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_time', models.DateTimeField()),
                ('edit_reason', models.CharField(blank=True, max_length=256)),
                ('latest', models.BooleanField()),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.attendee')),
                ('swag_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.swagoptions')),
            ],
            options={
                'verbose_name': 'Swag Logistics',
                'verbose_name_plural': 'Swag Logistics',
            },
        ),
    ]
