# Generated by Django 5.2.17 on 2026-09-03 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0003_alter_attendee_status'),
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buses',
            name='leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='conference.attendee'),
        ),
        migrations.AddField(
            model_name='buses',
            name='leader_phone_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
