# Generated by Django 4.2.30 on 2026-08-22 17:24

from django.db import migrations, models
import django.db.models.deletion
import logistics.models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_alter_buses_options_alter_bus_bus_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='bus_assignment',
        ),
        migrations.AddField(
            model_name='bus',
            name='bus_from_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bus_from', to='logistics.buses', validators=[logistics.models.validate_bus_to]),
        ),
        migrations.AddField(
            model_name='bus',
            name='bus_to_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bus_to', to='logistics.buses', validators=[logistics.models.validate_bus_to]),
        ),
        migrations.AlterField(
            model_name='bus',
            name='bus_to_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Early'), (1, 'Late'), (2, 'Return')], null=True),
        ),
        migrations.AlterField(
            model_name='buses',
            name='type',
            field=models.IntegerField(choices=[(0, 'Early'), (1, 'Late'), (2, 'Return')]),
        ),
    ]
