# Generated by Django 4.2.30 on 2026-08-22 20:19

from django.db import migrations, models
import django.db.models.deletion
import logistics.models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_remove_bus_bus_assignment_bus_bus_from_assignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buses',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='bus_from_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bus_from', to='logistics.buses', validators=[logistics.models.validate_bus_from, logistics.models.validate_bus_capacity]),
        ),
        migrations.AlterField(
            model_name='bus',
            name='bus_to_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bus_to', to='logistics.buses', validators=[logistics.models.validate_bus_to, logistics.models.validate_bus_capacity]),
        ),
    ]
