# Generated by Django 5.2.17 on 2026-09-03 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_buses_capacity_alter_bus_bus_from_assignment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acceptance',
            old_name='acceptance_note',
            new_name='acceptance_comment',
        ),
    ]
