# Generated by Django 5.2.17 on 2026-09-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_rename_acceptance_note_acceptance_acceptance_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptance',
            name='edit_reason',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='activities',
            name='edit_reason',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='bus',
            name='edit_reason',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='dinner',
            name='edit_reason',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='housingassignments',
            name='edit_reason',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='housingpreferences',
            name='edit_reason',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='marc',
            name='edit_reason',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='swag',
            name='edit_reason',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
