# Generated by Django 4.2.30 on 2026-08-18 17:46

import committee.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status', models.CharField(blank=True, max_length=32)),
                ('group', models.CharField(blank=True, max_length=64)),
                ('profile_image', models.ImageField(blank=True, upload_to=committee.models.committee_photo_path('committee_photos'))),
                ('profile_image_thumb', models.ImageField(blank=True, editable=False, upload_to=committee.models.committee_photo_path('thumbs'))),
            ],
        ),
        migrations.CreateModel(
            name='CommitteeRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.IntegerField(choices=[(0, 'Committee'), (1, 'Design'), (2, 'Logistics'), (3, 'Social'), (4, 'Programming'), (5, 'Swag'), (6, 'Photography'), (7, 'Web')])),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='committee.committeemember')),
                ('role_conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.quarcconference')),
            ],
            options={
                'ordering': ['role_type'],
            },
        ),
    ]
