# Generated by Django 5.2.17 on 2026-09-08 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommitteeRole',
        ),
    ]
