# Generated by Django 5.2.17 on 2026-09-08 22:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0002_delete_committeerole'),
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=32)),
                ('sort_order', models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
            ],
        ),
        migrations.CreateModel(
            name='CommitteeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='committee.committeemember')),
                ('quarc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.quarcconference')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='committee.committeerole')),
            ],
            options={
                'ordering': ['role__sort_order'],
            },
        ),
    ]
