# Generated by Django 5.2.17 on 2026-09-08 14:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abstract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('author_list', models.CharField(max_length=512)),
                ('funding_sources', models.CharField(max_length=512)),
                ('publications', models.CharField(blank=True, max_length=512)),
                ('figure', models.ImageField(blank=True, upload_to='abstract_figures')),
                ('figure_caption', models.CharField(blank=True, max_length=512)),
                ('abstract', models.CharField(max_length=2048)),
                ('seeking_internships', models.BooleanField()),
                ('seeking_positions', models.BooleanField()),
                ('elevator_pitch', models.BooleanField()),
                ('oral_presentation', models.BooleanField()),
                ('research_area', models.CharField(max_length=64)),
                ('research_goal', models.CharField(max_length=64)),
                ('research_group', models.CharField(max_length=64)),
                ('cqe_feature', models.BooleanField()),
                ('resume', models.FileField(blank=True, upload_to='resumes')),
                ('graduation_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QSECMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=64)),
                ('founder', models.BooleanField()),
            ],
            options={
                'verbose_name': 'QSEC Member',
                'verbose_name_plural': 'QSEC Members',
            },
        ),
        migrations.CreateModel(
            name='QuARCConference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('ordinal', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('marc_start_date', models.DateField(blank=True, null=True)),
                ('marc_end_date', models.DateField(blank=True, null=True)),
                ('registration_start', models.DateField(blank=True, null=True)),
                ('registration_end', models.DateField(blank=True, null=True)),
                ('abstract_submission_active', models.BooleanField(default=False)),
                ('university_industry_registration_active', models.BooleanField(default=False)),
                ('logistics_form_active', models.BooleanField(default=False)),
                ('program_active', models.BooleanField(default=False)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos')),
                ('homepage_image', models.ImageField(blank=True, null=True, upload_to='homepage_images')),
                ('primary_color', models.CharField(default='#2ea3f2', max_length=32)),
                ('secondary_color', models.CharField(default='#8300e9', max_length=32)),
                ('dark_color', models.CharField(default='#1a1a1a', max_length=32)),
                ('light_color', models.CharField(default='#ffffff', max_length=32)),
            ],
            options={
                'verbose_name': 'QuARC Conference',
                'verbose_name_plural': 'QuARC Conferences',
            },
        ),
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=32)),
                ('middle_name', models.CharField(blank=True, max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('suffix', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'Industry Personnel'), (1, 'Graduate Student'), (2, 'Postdoctoral Researcher'), (3, 'Research Staff'), (4, 'University Faculty'), (6, 'Undergraduate Student'), (50, 'Organizing Committee'), (100, 'Other')])),
                ('affiliation', models.CharField(blank=True, max_length=64)),
                ('abstract_title', models.CharField(blank=True, max_length=128, null=True)),
                ('authored_abstract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_abstract', to='conference.abstract')),
                ('quarc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.quarcconference')),
            ],
        ),
        migrations.AddField(
            model_name='abstract',
            name='attendee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.attendee'),
        ),
        migrations.CreateModel(
            name='AttendeeEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('subject', models.CharField(max_length=512)),
                ('text_message', models.TextField()),
                ('html_message', models.TextField(blank=True)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.attendee')),
            ],
            options={
                'verbose_name': 'Attendee Email',
                'verbose_name_plural': 'Attendee Emails',
            },
        ),
        migrations.CreateModel(
            name='ConferenceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=64)),
                ('location', models.CharField(max_length=64)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=2048)),
                ('quarc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.quarcconference')),
            ],
            options={
                'verbose_name': 'Conference Event',
                'verbose_name_plural': 'Conference Events',
            },
        ),
        migrations.CreateModel(
            name='QuARCQSECMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qsec_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.qsecmember')),
                ('quarc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.quarcconference')),
            ],
            options={
                'verbose_name': 'QSEC for QuARC',
                'verbose_name_plural': 'QSEC for QuARC',
            },
        ),
        migrations.CreateModel(
            name='ResearchArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_area', models.CharField(max_length=64)),
                ('quarc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.quarcconference')),
            ],
            options={
                'verbose_name': 'Research Area',
                'verbose_name_plural': 'Research Areas',
            },
        ),
        migrations.CreateModel(
            name='ResearchGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_goal', models.CharField(max_length=64)),
                ('quarc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.quarcconference')),
            ],
            options={
                'verbose_name': 'Research Goal',
                'verbose_name_plural': 'Research Goals',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conference.conferenceevent')),
                ('quarc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.quarcconference')),
            ],
            options={
                'verbose_name': 'QuARC Session',
                'verbose_name_plural': 'QuARC Sessions',
            },
        ),
        migrations.CreateModel(
            name='SessionAbstract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('abstract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.abstract')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.session')),
            ],
            options={
                'verbose_name': 'QuARC Session Abstract Assignment',
                'verbose_name_plural': 'QuARC Session Abstract Assignments',
            },
        ),
    ]
