# Generated by Django 4.2.30 on 2026-08-19 13:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=32)),
                ('middle_name', models.CharField(blank=True, max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('suffix', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'Industry Personnel'), (1, 'Student'), (2, 'Postdoctoral Researcher'), (3, 'Research Staff'), (4, 'University Faculty'), (5, 'Quarc Chair'), (100, 'Other')])),
                ('affiliation', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='DinnerOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Dinner Option',
                'verbose_name_plural': 'Dinner Options',
            },
        ),
        migrations.CreateModel(
            name='QSECMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=64)),
                ('founder', models.BooleanField()),
            ],
            options={
                'verbose_name': 'QSEC Member',
                'verbose_name_plural': 'QSEC Members',
            },
        ),
        migrations.CreateModel(
            name='QuARCConference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('ordinal', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField(blank=True)),
                ('marc_start_date', models.DateField(blank=True)),
                ('marc_end_date', models.DateField(blank=True)),
                ('registration_start', models.DateField(blank=True)),
                ('registration_end', models.DateField(blank=True)),
                ('abstract_submission_active', models.BooleanField(default=False)),
                ('university_industry_registration_active', models.BooleanField(default=False)),
                ('logistics_form_active', models.BooleanField(default=False)),
                ('logo', models.ImageField(blank=True, upload_to='logos')),
                ('homepage_image', models.ImageField(blank=True, upload_to='homepage_images')),
            ],
            options={
                'verbose_name': 'QuARC Conference',
                'verbose_name_plural': 'QuARC Conferences',
            },
        ),
        migrations.CreateModel(
            name='SwagOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=32)),
                ('url', models.CharField(blank=True, max_length=32)),
                ('quarc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.quarcconference')),
            ],
            options={
                'verbose_name': 'Swag Option',
                'verbose_name_plural': 'Swag Options',
            },
        ),
        migrations.CreateModel(
            name='QuARCQSECMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qsec_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.qsecmember')),
                ('quarc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.quarcconference')),
            ],
            options={
                'verbose_name': 'QSEC for QuARC',
                'verbose_name_plural': 'QSEC for QuARC',
            },
        ),
        migrations.CreateModel(
            name='LogisticsSwag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_time', models.DateTimeField()),
                ('latest', models.BooleanField()),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.attendee')),
                ('swag_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.swagoptions')),
            ],
            options={
                'verbose_name': 'Swag Logistics',
                'verbose_name_plural': 'Swag Logistics',
            },
        ),
        migrations.CreateModel(
            name='LogisticsMARC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_time', models.DateTimeField()),
                ('latest', models.BooleanField()),
                ('attending_marc', models.BooleanField(null=True)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.attendee')),
            ],
            options={
                'verbose_name': 'MARC Logistics',
                'verbose_name_plural': 'MARC Logistics',
            },
        ),
        migrations.CreateModel(
            name='LogisticsHousingPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_time', models.DateTimeField()),
                ('latest', models.BooleanField()),
                ('overnight_required', models.BooleanField()),
                ('needs_roommate', models.BooleanField(blank=True)),
                ('preferred_roommate_name', models.CharField(blank=True, max_length=64)),
                ('gender', models.CharField(blank=True, max_length=32)),
                ('preferred_roommate_gender', models.CharField(blank=True, max_length=32)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.attendee')),
                ('preferred_roommate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_roommate', to='conference.attendee')),
            ],
            options={
                'verbose_name': 'Housing Preferences Logistics',
                'verbose_name_plural': 'Housing Preferences Logistics',
            },
        ),
        migrations.CreateModel(
            name='LogisticsHousingAssignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_time', models.DateTimeField()),
                ('latest', models.BooleanField()),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.attendee')),
                ('roommate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roommate', to='conference.attendee')),
            ],
            options={
                'verbose_name': 'Housing Assignment Logistics',
                'verbose_name_plural': 'Housing Assignment Logistics',
            },
        ),
        migrations.CreateModel(
            name='LogisticsDinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_time', models.DateTimeField()),
                ('latest', models.BooleanField()),
                ('dinner_required', models.BooleanField()),
                ('vegetarian', models.BooleanField(blank=True, null=True)),
                ('vegan', models.BooleanField(blank=True, null=True)),
                ('gluten_free', models.BooleanField(blank=True, null=True)),
                ('kosher', models.BooleanField(blank=True, null=True)),
                ('halal', models.BooleanField(blank=True, null=True)),
                ('other_restriction', models.CharField(blank=True, max_length=64)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.attendee')),
                ('dinner_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conference.dinneroptions')),
            ],
            options={
                'verbose_name': 'Dinner Logistics',
                'verbose_name_plural': 'Dinner Logistics',
            },
        ),
        migrations.CreateModel(
            name='LogisticsBus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_time', models.DateTimeField()),
                ('latest', models.BooleanField()),
                ('bus_to_required', models.BooleanField()),
                ('bus_to_type', models.IntegerField(blank=True, choices=[(0, 'Early'), (1, 'Late')], null=True)),
                ('bus_from_required', models.BooleanField()),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.attendee')),
            ],
            options={
                'verbose_name': 'Bus Logistics',
                'verbose_name_plural': 'Bus Logistics',
            },
        ),
        migrations.CreateModel(
            name='LogisticsActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_time', models.DateTimeField()),
                ('latest', models.BooleanField()),
                ('winter_activities', models.BooleanField()),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.attendee')),
            ],
            options={
                'verbose_name': 'Winter Activities Logistics',
                'verbose_name_plural': 'Winter Activities Logistics',
            },
        ),
        migrations.AddField(
            model_name='dinneroptions',
            name='quarc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.quarcconference'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='quarc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.quarcconference'),
        ),
        migrations.CreateModel(
            name='Acceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_time', models.DateTimeField()),
                ('latest', models.BooleanField()),
                ('accepted', models.BooleanField()),
                ('acceptance_note', models.CharField(blank=True, max_length=256)),
                ('dropped', models.BooleanField(null=True)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.attendee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Abstract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('author_list', models.CharField(max_length=512)),
                ('funding_sources', models.CharField(max_length=512)),
                ('publications', models.CharField(max_length=512)),
                ('figure', models.ImageField(blank=True, upload_to='abstract_figures')),
                ('figure_caption', models.CharField(max_length=512)),
                ('abstract', models.CharField(max_length=2048)),
                ('seeking_internships', models.BooleanField()),
                ('seeking_positions', models.BooleanField()),
                ('elevator_pitch', models.BooleanField()),
                ('oral_presentation', models.BooleanField()),
                ('research_area', models.CharField(max_length=64)),
                ('research_group', models.CharField(max_length=64)),
                ('cqe_feature', models.BooleanField()),
                ('resume', models.FileField(blank=True, upload_to='resumes')),
                ('graduation_date', models.DateField(null=True)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.attendee')),
            ],
        ),
        migrations.AddConstraint(
            model_name='logisticshousingassignments',
            constraint=models.CheckConstraint(check=models.Q(('attendee__lte', models.F('roommate'))), name='conference_logisticshousingassignments_alphabetize_roommates'),
        ),
    ]
