# Generated by Django 5.2.17 on 2026-09-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstract',
            name='figure_caption',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
