# Generated by Django 4.2.30 on 2026-08-19 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='logisticshousingassignments',
            name='conference_logisticshousingassignments_alphabetize_roommates',
        ),
    ]
