# Generated by Django 5.2.17 on 2026-09-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarcconference',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='homepage_images'),
        ),
    ]
