# Generated by Django 5.2.17 on 2026-09-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarcconference',
            name='homepage_image',
            field=models.ImageField(blank=True, null=True, upload_to='homepage_images'),
        ),
        migrations.AlterField(
            model_name='quarcconference',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos'),
        ),
        migrations.AlterField(
            model_name='quarcconference',
            name='marc_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quarcconference',
            name='marc_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quarcconference',
            name='registration_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quarcconference',
            name='registration_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quarcconference',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
