# Generated by Django 5.2.17 on 2026-09-05 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendeeEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('subject', models.CharField(max_length=512)),
                ('text_message', models.TextField()),
                ('html_message', models.TextField(blank=True)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.attendee')),
            ],
            options={
                'verbose_name': 'Attendee Email',
                'verbose_name_plural': 'Attendee Emails',
            },
        ),
    ]
