# Generated by Django 5.2.17 on 2026-09-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0002_alter_abstract_figure_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstract',
            name='publications',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
