# Generated by Django 5.2.17 on 2026-09-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0002_alter_quarcconference_homepage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='status',
            field=models.IntegerField(choices=[(0, 'Industry Personnel'), (1, 'Graduate Student'), (2, 'Postdoctoral Researcher'), (3, 'Research Staff'), (4, 'University Faculty'), (6, 'Undergraduate Student'), (50, 'Organizing Committee'), (100, 'Other')]),
        ),
    ]
