# Generated by Django 4.2.30 on 2026-08-20 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0002_remove_logisticshousingassignments_conference_logisticshousingassignments_alphabetize_roommates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logisticshousingassignments',
            name='roommate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roommate', to='conference.attendee'),
        ),
    ]
