# Generated by Django 4.2.30 on 2026-08-22 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0003_alter_logisticshousingassignments_roommate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Early'), (1, 'Late')])),
                ('number', models.IntegerField()),
                ('quarc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.quarcconference')),
            ],
            options={
                'verbose_name': 'Swag Option',
                'verbose_name_plural': 'Swag Options',
            },
        ),
        migrations.AddField(
            model_name='logisticsbus',
            name='bus_assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='conference.buses'),
        ),
    ]
