# Generated by Django 4.2.30 on 2026-08-22 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0004_buses_logisticsbus_bus_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buses',
            name='quarc',
        ),
        migrations.RemoveField(
            model_name='dinneroptions',
            name='quarc',
        ),
        migrations.RemoveField(
            model_name='logisticsactivities',
            name='attendee',
        ),
        migrations.RemoveField(
            model_name='logisticsbus',
            name='attendee',
        ),
        migrations.RemoveField(
            model_name='logisticsbus',
            name='bus_assignment',
        ),
        migrations.RemoveField(
            model_name='logisticsdinner',
            name='attendee',
        ),
        migrations.RemoveField(
            model_name='logisticsdinner',
            name='dinner_option',
        ),
        migrations.RemoveField(
            model_name='logisticshousingassignments',
            name='attendee',
        ),
        migrations.RemoveField(
            model_name='logisticshousingassignments',
            name='roommate',
        ),
        migrations.RemoveField(
            model_name='logisticshousingpreferences',
            name='attendee',
        ),
        migrations.RemoveField(
            model_name='logisticshousingpreferences',
            name='preferred_roommate',
        ),
        migrations.RemoveField(
            model_name='logisticsmarc',
            name='attendee',
        ),
        migrations.RemoveField(
            model_name='logisticsswag',
            name='attendee',
        ),
        migrations.RemoveField(
            model_name='logisticsswag',
            name='swag_option',
        ),
        migrations.RemoveField(
            model_name='swagoptions',
            name='quarc',
        ),
        migrations.DeleteModel(
            name='Acceptance',
        ),
        migrations.DeleteModel(
            name='Buses',
        ),
        migrations.DeleteModel(
            name='DinnerOptions',
        ),
        migrations.DeleteModel(
            name='LogisticsActivities',
        ),
        migrations.DeleteModel(
            name='LogisticsBus',
        ),
        migrations.DeleteModel(
            name='LogisticsDinner',
        ),
        migrations.DeleteModel(
            name='LogisticsHousingAssignments',
        ),
        migrations.DeleteModel(
            name='LogisticsHousingPreferences',
        ),
        migrations.DeleteModel(
            name='LogisticsMARC',
        ),
        migrations.DeleteModel(
            name='LogisticsSwag',
        ),
        migrations.DeleteModel(
            name='SwagOptions',
        ),
    ]
