# Generated by Django 4.2.30 on 2026-08-22 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0005_remove_buses_quarc_remove_dinneroptions_quarc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=64)),
                ('location', models.CharField(max_length=64)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True)),
                ('quarc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.quarcconference')),
            ],
            options={
                'verbose_name': 'QuARC Event',
                'verbose_name_plural': 'QuARC Events',
            },
        ),
    ]
