# Generated by Django 4.2.30 on 2026-08-22 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0006_programevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programevent',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
