# Generated by Django 4.2.30 on 2026-08-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0007_alter_programevent_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='programevent',
            name='description',
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
