# Generated by Django 4.2.30 on 2026-08-23 17:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0008_programevent_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='conference.programevent')),
                ('quarc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.quarcconference')),
            ],
        ),
        migrations.CreateModel(
            name='SessionAbstract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('abstract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.abstract')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.session')),
            ],
        ),
    ]
