# Generated by Django 4.2.30 on 2026-08-23 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0009_session_sessionabstract'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name': 'QuARC Session', 'verbose_name_plural': 'QuARC Sessions'},
        ),
        migrations.AlterModelOptions(
            name='sessionabstract',
            options={'verbose_name': 'QuARC Session Abstract Assignment', 'verbose_name_plural': 'QuARC Session Abstract Assignments'},
        ),
        migrations.AlterField(
            model_name='session',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conference.programevent'),
        ),
    ]
