# Generated by Django 4.2.30 on 2026-08-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0010_alter_session_options_alter_sessionabstract_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstract',
            name='graduation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
