# Generated by Django 5.2.17 on 2026-09-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0011_alter_abstract_graduation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarcconference',
            name='dark_color',
            field=models.CharField(default='#1a1a1a', max_length=32),
        ),
        migrations.AddField(
            model_name='quarcconference',
            name='light_color',
            field=models.CharField(default='#ffffff', max_length=32),
        ),
        migrations.AddField(
            model_name='quarcconference',
            name='primary_color',
            field=models.CharField(default='#2ea3f2', max_length=32),
        ),
        migrations.AddField(
            model_name='quarcconference',
            name='secondary_color',
            field=models.CharField(default='#8300e9', max_length=32),
        ),
    ]
