# Generated by Django 5.2.17 on 2026-09-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0012_quarcconference_dark_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarcconference',
            name='program_active',
            field=models.BooleanField(default=False),
        ),
    ]
