# Generated by Django 5.2.17 on 2026-09-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0014_alter_attendee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='status',
            field=models.IntegerField(choices=[(0, 'Industry Personnel'), (1, 'Graduate Student'), (2, 'Postdoctoral Researcher'), (3, 'Research Staff'), (4, 'University Faculty'), (5, 'Organizing Committee'), (6, 'Undergraduate Student'), (100, 'Other')]),
        ),
    ]
