# Generated by Django 5.2.17 on 2026-09-03 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0015_alter_attendee_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programevent',
            options={'verbose_name': 'Conference Event', 'verbose_name_plural': 'Conference Events'},
        ),
        migrations.AddField(
            model_name='abstract',
            name='research_goal',
            field=models.CharField(default='AMO', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='abstract',
            name='research_area',
            field=models.CharField(max_length=32),
        ),
        migrations.CreateModel(
            name='ResearchArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_area', models.CharField(max_length=32)),
                ('quarc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.quarcconference')),
            ],
            options={
                'verbose_name': 'Research Area',
                'verbose_name_plural': 'Research Areas',
            },
        ),
        migrations.CreateModel(
            name='ResearchGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_goal', models.CharField(max_length=32)),
                ('quarc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.quarcconference')),
            ],
            options={
                'verbose_name': 'Research Goal',
                'verbose_name_plural': 'Research Goals',
            },
        ),
    ]
