# Generated by Django 5.2.17 on 2026-09-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0016_alter_programevent_options_abstract_research_goal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstract',
            name='research_area',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='abstract',
            name='research_goal',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='researcharea',
            name='research_area',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='researchgoal',
            name='research_goal',
            field=models.CharField(max_length=64),
        ),
    ]
