# Generated by Django 5.2.17 on 2026-09-03 19:28

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conference', '0001_initial'),
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DinnerOptionsProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Dinner Option',
                'verbose_name_plural': 'Dinner Options',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('logistics.dinneroptions',),
        ),
        migrations.CreateModel(
            name='ProgramEventProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Conference Event',
                'verbose_name_plural': 'Conference Events',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('conference.programevent',),
        ),
        migrations.CreateModel(
            name='QSECMemberProxy',
            fields=[
            ],
            options={
                'verbose_name': 'QSEC Member',
                'verbose_name_plural': 'QSEC Members',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('conference.qsecmember',),
        ),
        migrations.CreateModel(
            name='QuARCConferenceProxy',
            fields=[
            ],
            options={
                'verbose_name': 'QuARC Conference',
                'verbose_name_plural': 'QuARC Conferences',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('conference.quarcconference',),
        ),
        migrations.CreateModel(
            name='QuARCQSECMembersProxy',
            fields=[
            ],
            options={
                'verbose_name': 'QSEC for QuARC',
                'verbose_name_plural': 'QSEC for QuARC',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('conference.quarcqsecmembers',),
        ),
        migrations.CreateModel(
            name='ResearchAreaProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Research Area',
                'verbose_name_plural': 'Research Areas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('conference.researcharea',),
        ),
        migrations.CreateModel(
            name='ResearchGoalProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Research Goal',
                'verbose_name_plural': 'Research Goals',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('conference.researchgoal',),
        ),
        migrations.CreateModel(
            name='SwagOptionsProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Swag Option',
                'verbose_name_plural': 'Swag Options',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('logistics.swagoptions',),
        ),
    ]
