# Generated by Django 5.2.17 on 2026-09-05 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0002_attendeeemail'),
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendeeEmailProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Attendee Email',
                'verbose_name_plural': 'Attendee Emails',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('conference.attendeeemail',),
        ),
    ]
